#
# This docker compose file is usable for demo purposes:
#
version: '3.4'
services:

  loginbuddy-demosetup:
    image: saschazegerman/loginbuddy:latest-demo
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "9010:9010"
      - "9011:9011"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8000,suspend=n,server=y \
        -Dcom.sun.management.jmxremote \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Dcom.sun.management.jmxremote.port=9010 \
        -Djava.rmi.server.hostname=local.loginbuddy.net \
        -Dcom.sun.management.jmxremote.rmi.port=9011 \
        -Dcom.sun.management.jmxremote.local.only=false"
      - "SUPPORT_OIDCDR=true"
      - "SSL_PWD=${SSL_PWD}"
    volumes:
      - ./dev/loginbuddy.p12:/usr/local/tomcat/ssl/loginbuddy.p12

  loginbuddy-oidcdr:
    image: saschazegerman/loginbuddy:latest-oidcdr
    restart: always