#
# This docker compose file is usable for development purposes:
#
# NOTE: use this only for local development purposes!
#
version: '3.4'
services:

  loginbuddy-selfissued:
    image: saschazegerman/loginbuddy:latest-selfissued
    restart: always
    ports:
      - "445:445"
      - "8002:8002"
      - "9012:9012"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8002,suspend=n,server=y -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9012 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

  loginbuddy-test:
    image: saschazegerman/loginbuddy:latest-demo
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "9010:9010"
    volumes:
      - ./config.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/config.json
      - ./discovery.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/discovery.json
      - ./permissions.policy:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/permissions.policy
      - ./server_loginbuddy.png:/usr/local/tomcat/webapps/ROOT/images/server_loginbuddy.png
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

#  loginbuddy-sidecar-test:
#    image: saschazegerman/loginbuddy:latest-sidecar
#    restart: always
#    ports:
#      - "444:444"
#      - "8001:8001"
#      - "9011:9011"
#    volumes:
#      - ./config.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/config.json
#      - ./discovery.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/discovery.json
#      - ./permissions.policy:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/permissions.policy
#      - ./server_loginbuddy.png:/usr/local/tomcat/webapps/ROOT/images/server_loginbuddy.png
#    environment:
#      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8001,suspend=n,server=y -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
